let superHeroeName = 'Batman';
let name = 'Bruce Wayne';
let fly = false;
let hasBatmobile = true;
let freeTime = null;
console.log('superHeroeName:', superHeroeName, typeof superHeroeName);
console.log('name:', name, typeof name);
console.log('fly:', fly, typeof fly);
console.log('hasBatmobile:', hasBatmobile, typeof hasBatmobile);
console.log('freeTime:', freeTime, typeof freeTime);