let number = 9;
console.log('9 times 1 equals ' + number);
console.log('9 times 2 equals ' + number * 2);
console.log('9 times 3 equals ' + number * 3);
console.log('9 times 4 equals ' + number * 4);
console.log('9 times 5 equals ' + number * 5);
console.log('9 times 6 equals ' + number * 6);
console.log('9 times 7 equals ' + number * 7);
console.log('9 times 8 equals ' + number * 8);
console.log('9 times 9 equals ' + number * 9);
console.log('9 times 10 equals ' + number * 10);