var firstName = 'Harpreet';
var lastName = 'Dhillon';
var age = 31;
var dateOfBirth = '01/01/1987';
var address = 'Winnipeg';
console.log('First Name:', firstName);
console.log('Last Name:', lastName);
console.log('Age:', age);
console.log('DOB:', dateOfBirth);
console.log('Address:', address);
