let firstName = 'Harpreet';
let lastName = 'Dhillon';
let age = 31;
let dateOfBirth = '01/01/1987';
let address = 'Winnipeg';
console.log('First Name:', firstName);
console.log('Last Name:', lastName);
console.log('Age:', age);
console.log('DOB:', dateOfBirth);
console.log('Address:', address);
