const firstName = 'Harpreet';
const lastName = 'Dhillon';
const age = 31;
const dateOfBirth = '01/01/1987';
const address = 'Winnipeg';
console.log('First Name:', firstName);
console.log('Last Name:', lastName);
console.log('Age:', age);
console.log('DOB:', dateOfBirth);
console.log('Address:', address);